#!/usr/bin/env bash
# install.sh — Idempotent installation script for the Bastion service on Ubuntu
# Run as root. Safe to run multiple times.
set -euo pipefail

BASTION_ROOT="/opt/bastion"
BASTION_USER="bastion"
BASTION_GROUP="bastion"
BASTION_USERS_GROUP="bastion-users"
PYTHON_MIN="3.11"
REDIS_VERSION="7"

log()  { echo "[bastion-install] $*"; }
warn() { echo "[bastion-install] WARNING: $*" >&2; }
die()  { echo "[bastion-install] ERROR: $*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "This script must be run as root."

# ── System dependencies ───────────────────────────────────────────────────────
log "Updating package lists..."
apt-get update -qq

log "Installing system dependencies..."
apt-get install -y -qq \
    python3.11 python3.11-venv python3.11-dev \
    python3-pip \
    redis-server \
    openssh-client \
    age \
    git \
    curl \
    build-essential \
    libpq-dev \
    libffi-dev \
    libssl-dev

# ── System user and groups ────────────────────────────────────────────────────
log "Creating bastion system user and groups..."

getent group "$BASTION_GROUP" >/dev/null 2>&1 || groupadd --system "$BASTION_GROUP"
getent group "$BASTION_USERS_GROUP" >/dev/null 2>&1 || groupadd "$BASTION_USERS_GROUP"

id "$BASTION_USER" >/dev/null 2>&1 || useradd \
    --system \
    --gid "$BASTION_GROUP" \
    --home-dir "$BASTION_ROOT" \
    --no-create-home \
    --shell /usr/sbin/nologin \
    "$BASTION_USER"

# ── Directory structure ───────────────────────────────────────────────────────
log "Creating directory structure under $BASTION_ROOT..."

dirs=(
    "$BASTION_ROOT"
    "$BASTION_ROOT/data"
    "$BASTION_ROOT/ca"
    "$BASTION_ROOT/recordings"
    "$BASTION_ROOT/run"
    "$BASTION_ROOT/logs"
    "$BASTION_ROOT/venv"
    "$BASTION_ROOT/app"
)

for dir in "${dirs[@]}"; do
    mkdir -p "$dir"
done

# Sensitive directories — only bastion user can read
chmod 700 "$BASTION_ROOT/ca"
chmod 700 "$BASTION_ROOT/data"
chmod 750 "$BASTION_ROOT/recordings"
chmod 750 "$BASTION_ROOT/run"
chmod 755 "$BASTION_ROOT/app"

chown -R "$BASTION_USER:$BASTION_GROUP" "$BASTION_ROOT"

# Allow bastion-users group to access the run socket directory
chmod 770 "$BASTION_ROOT/run"
chown "$BASTION_USER:$BASTION_USERS_GROUP" "$BASTION_ROOT/run"

# ── Python virtual environment ────────────────────────────────────────────────
log "Setting up Python virtual environment..."

if [[ ! -f "$BASTION_ROOT/venv/bin/python" ]]; then
    python3.11 -m venv "$BASTION_ROOT/venv"
    chown -R "$BASTION_USER:$BASTION_GROUP" "$BASTION_ROOT/venv"
fi

# ── Application code ──────────────────────────────────────────────────────────
log "Copying application code..."
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_SRC="$(dirname "$SCRIPT_DIR")"

rsync -a --delete \
    --exclude='.git' \
    --exclude='.amazonq' \
    --exclude='*.pyc' \
    --exclude='__pycache__' \
    --exclude='.env' \
    --exclude='*.db' \
    --exclude='recordings/' \
    --exclude='logs/' \
    "$APP_SRC/" "$BASTION_ROOT/app/"

chown -R "$BASTION_USER:$BASTION_GROUP" "$BASTION_ROOT/app"

# ── Python dependencies ───────────────────────────────────────────────────────
log "Installing Python dependencies..."
sudo -u "$BASTION_USER" "$BASTION_ROOT/venv/bin/pip" install --quiet --upgrade pip
sudo -u "$BASTION_USER" "$BASTION_ROOT/venv/bin/pip" install --quiet -r "$BASTION_ROOT/app/requirements.txt"

# ── CLI symlinks ─────────────────────────────────────────────────────────────
log "Installing bastion CLI tools..."
cat > /usr/local/bin/bastion << 'EOF'
#!/usr/bin/env bash
# Bastion CLI wrapper — runs as the current user via the API socket
exec /opt/bastion/venv/bin/python -m cli.main "$@"
EOF
chmod 755 /usr/local/bin/bastion

cat > /usr/local/bin/bastion-admin << 'EOF'
#!/usr/bin/env bash
# Bastion Admin CLI wrapper — requires bastion group membership
exec /opt/bastion/venv/bin/python -m cli.admin "$@"
EOF
chmod 755 /usr/local/bin/bastion-admin

# ── Environment file ──────────────────────────────────────────────────────────
if [[ ! -f "$BASTION_ROOT/.env" ]]; then
    log "Generating initial .env file..."
    SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(64))")
    cat > "$BASTION_ROOT/.env" << EOF
# Bastion environment configuration
# Generated by install.sh — review and customise before starting services

SECRET_KEY=${SECRET_KEY}
ENVIRONMENT=production
HA_MODE=false
NODE_ID=node-1

DB_BACKEND=sqlite
DB_URL=sqlite+aiosqlite:////opt/bastion/data/bastion.db

REDIS_URL=redis://localhost:6379/0

# CA key passphrase — set this to encrypt the CA private key at rest
# CA_KEY_PASSPHRASE=

SSH_CERT_VALIDITY_HOURS=8
RECORDINGS_ENABLED=true
RECORDINGS_STORAGE=local

# Master key for per-admin recording decrypt key derivation
# RECORDINGS_MASTER_KEY=

TOTP_ISSUER=Bastion
MFA_EMAIL_CODE_EXPIRE_MINUTES=10
RATE_LIMIT_AUTH_PER_MINUTE=10
ANOMALY_SCORE_ALERT_THRESHOLD=70
PACKAGE_CHECK_INTERVAL_HOURS=6
SSH_KEY_MAX_AGE_DAYS=365
CERT_EXPIRY_WARN_MINUTES=60

# Dual approval — set to true for multi-admin deployments
DUAL_APPROVAL_REQUIRED=false
DUAL_APPROVAL_WINDOW_MINUTES=30
EOF
    chmod 600 "$BASTION_ROOT/.env"
    chown "$BASTION_USER:$BASTION_GROUP" "$BASTION_ROOT/.env"
    log "Generated .env at $BASTION_ROOT/.env — please review before starting services."
fi

# ── SSH CA keypair ────────────────────────────────────────────────────────────
if [[ ! -f "$BASTION_ROOT/ca/bastion_ca" ]]; then
    log "Generating SSH CA keypair..."
    # Generate a random CA key passphrase and store it in the .env
    CA_PASSPHRASE=$(python3 -c "import secrets; print(secrets.token_hex(32))")
    echo "CA_KEY_PASSPHRASE=${CA_PASSPHRASE}" >> "$BASTION_ROOT/.env"
    sudo -u "$BASTION_USER" "$BASTION_ROOT/venv/bin/python" -c "
import sys
sys.path.insert(0, '/opt/bastion/app')
from bastion.crypto.ca import generate_ca_keypair
from pathlib import Path
generate_ca_keypair(Path('/opt/bastion/ca/bastion_ca'), passphrase=b'${CA_PASSPHRASE}')
"
    log "CA keypair generated at $BASTION_ROOT/ca/bastion_ca (encrypted with passphrase)"
    log "IMPORTANT: Back up $BASTION_ROOT/ca/bastion_ca and the CA_KEY_PASSPHRASE securely."
fi

# ── Redis configuration ───────────────────────────────────────────────────────
log "Configuring Redis..."
cat > /etc/redis/redis.conf.d/bastion.conf << 'EOF' 2>/dev/null || true
bind 127.0.0.1
protected-mode yes
EOF
systemctl enable redis-server --quiet
systemctl restart redis-server

# ── Systemd service units ─────────────────────────────────────────────────────
log "Installing systemd service units..."

cat > /etc/systemd/system/bastion-api.service << EOF
[Unit]
Description=Bastion API Service
After=network.target redis-server.service
Requires=redis-server.service

[Service]
Type=exec
User=${BASTION_USER}
Group=${BASTION_GROUP}
WorkingDirectory=${BASTION_ROOT}/app
Environment=PYTHONPATH=${BASTION_ROOT}/app
EnvironmentFile=${BASTION_ROOT}/.env
ExecStart=${BASTION_ROOT}/venv/bin/uvicorn bastion_api.main:app \\
    --uds ${BASTION_ROOT}/run/bastion-api.sock \\
    --workers 2 \\
    --log-level warning
ExecStartPost=/bin/chmod 660 ${BASTION_ROOT}/run/bastion-api.sock
ExecStartPost=/bin/chown ${BASTION_USER}:${BASTION_USERS_GROUP} ${BASTION_ROOT}/run/bastion-api.sock
Restart=on-failure
RestartSec=5
NoNewPrivileges=yes
PrivateTmp=yes
ProtectSystem=strict
ReadWritePaths=${BASTION_ROOT}
CapabilityBoundingSet=
AmbientCapabilities=

[Install]
WantedBy=multi-user.target
EOF

cat > /etc/systemd/system/bastion-admin.service << EOF
[Unit]
Description=Bastion Admin API Service
After=network.target redis-server.service
Requires=redis-server.service

[Service]
Type=exec
User=${BASTION_USER}
Group=${BASTION_GROUP}
WorkingDirectory=${BASTION_ROOT}/app
Environment=PYTHONPATH=${BASTION_ROOT}/app
EnvironmentFile=${BASTION_ROOT}/.env
ExecStart=${BASTION_ROOT}/venv/bin/uvicorn bastion_admin.main:app \\
    --uds ${BASTION_ROOT}/run/bastion-admin.sock \\
    --workers 1 \\
    --log-level warning
ExecStartPost=/bin/chmod 660 ${BASTION_ROOT}/run/bastion-admin.sock
ExecStartPost=/bin/chown ${BASTION_USER}:${BASTION_GROUP} ${BASTION_ROOT}/run/bastion-admin.sock
Restart=on-failure
RestartSec=5
NoNewPrivileges=yes
PrivateTmp=yes
ProtectSystem=strict
ReadWritePaths=${BASTION_ROOT}
CapabilityBoundingSet=
AmbientCapabilities=

[Install]
WantedBy=multi-user.target
EOF

cat > /etc/systemd/system/bastion-worker.service << EOF
[Unit]
Description=Bastion Celery Worker
After=network.target redis-server.service
Requires=redis-server.service

[Service]
Type=exec
User=${BASTION_USER}
Group=${BASTION_GROUP}
WorkingDirectory=${BASTION_ROOT}/app
Environment=PYTHONPATH=${BASTION_ROOT}/app
EnvironmentFile=${BASTION_ROOT}/.env
ExecStart=${BASTION_ROOT}/venv/bin/celery -A workers.celery_app worker \\
    --loglevel=warning \\
    --concurrency=4 \\
    --queues=celery
Restart=on-failure
RestartSec=10
NoNewPrivileges=yes
PrivateTmp=yes
ProtectSystem=strict
ReadWritePaths=${BASTION_ROOT}

[Install]
WantedBy=multi-user.target
EOF

cat > /etc/systemd/system/bastion-beat.service << EOF
[Unit]
Description=Bastion Celery Beat Scheduler
After=network.target redis-server.service
Requires=redis-server.service

[Service]
Type=exec
User=${BASTION_USER}
Group=${BASTION_GROUP}
WorkingDirectory=${BASTION_ROOT}/app
Environment=PYTHONPATH=${BASTION_ROOT}/app
EnvironmentFile=${BASTION_ROOT}/.env
ExecStart=${BASTION_ROOT}/venv/bin/celery -A workers.celery_app beat \\
    --loglevel=warning \\
    --schedule=${BASTION_ROOT}/data/celerybeat-schedule
Restart=on-failure
RestartSec=10
NoNewPrivileges=yes
PrivateTmp=yes
ProtectSystem=strict
ReadWritePaths=${BASTION_ROOT}

[Install]
WantedBy=multi-user.target
EOF

# ── Enable and start services ─────────────────────────────────────────────────
log "Enabling and starting Bastion services..."
systemctl daemon-reload
systemctl enable bastion-api bastion-admin bastion-worker bastion-beat
systemctl restart bastion-api bastion-admin bastion-worker bastion-beat

# ── SSH hardening for the bastion host itself ─────────────────────────────────
log "Applying SSH hardening to the bastion host..."
mkdir -p /etc/ssh/sshd_config.d
cat > /etc/ssh/sshd_config.d/99-bastion-host.conf << 'EOF'
# Bastion host SSH hardening
PermitRootLogin prohibit-password
PasswordAuthentication no
ChallengeResponseAuthentication no
MaxAuthTries 3
LoginGraceTime 30
X11Forwarding no
AllowGroups bastion-users root
PrintLastLog yes
LogLevel VERBOSE
EOF

sshd -t && systemctl restart sshd
log "SSH hardening applied to bastion host."

log ""
log "═══════════════════════════════════════════════════════"
log " Bastion installation complete."
log "═══════════════════════════════════════════════════════"
log ""
log " Next steps:"
log "   1. Review and update $BASTION_ROOT/.env"
log "   2. Back up the CA private key: $BASTION_ROOT/ca/bastion_ca"
log "   3. Add users to the bastion-users group: usermod -aG bastion-users <username>"
log "   4. Create the first admin user via the admin API"
log "   5. Onboard your first server: bastion connect <hostname>"
log ""
log " Service status:"
log "   systemctl status bastion-api bastion-admin bastion-worker bastion-beat"
log ""
